import { Link, useLocation } from "react-router-dom";
import { useAuth } from "../hooks/useAuth";
import Button from "../components/UI/Button";
import Card from "../components/UI/Card";
import { useEffect } from "react";

const Home = () => {
  const { user } = useAuth();
  const location = useLocation();

  // Handle scroll to section when navigating from navbar
  useEffect(() => {
    if (location.state?.scrollTo) {
      const element = document.getElementById(location.state.scrollTo);
      if (element) {
        setTimeout(() => {
          element.scrollIntoView({ behavior: "smooth", block: "start" });
        }, 100);
      }
      // Clear the state
      window.history.replaceState({}, document.title);
    }
  }, [location]);

  const features = [
    {
      title: "AI-Powered Questions",
      description:
        "Get dynamic, role-specific questions generated by advanced AI that adapt to your experience level",
      icon: "🤖",
      color: "from-blue-500 to-blue-600",
    },
    {
      title: "Voice Recognition",
      description:
        "Practice speaking naturally with real-time voice capture and accurate transcription using Whisper AI",
      icon: "🎤",
      color: "from-purple-500 to-purple-600",
    },
    {
      title: "Instant Feedback",
      description:
        "Receive detailed analysis, scoring, and personalized suggestions to improve your answers",
      icon: "✨",
      color: "from-green-500 to-green-600",
    },
    {
      title: "Track Progress",
      description:
        "Monitor your improvement across multiple interview sessions with detailed analytics",
      icon: "📈",
      color: "from-orange-500 to-orange-600",
    },
  ];

  const stats = [
    { value: "10K+", label: "Active Users" },
    { value: "50K+", label: "Interviews Completed" },
    { value: "95%", label: "Success Rate" },
    { value: "4.9", label: "User Rating" },
  ];

  const scrollToFeatures = () => {
    const element = document.getElementById("features");
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-blue-200 via-purple-800 to-pink-600 text-white">
        {/* Animated background */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-white rounded-full blur-3xl animate-pulse"></div>
          <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-white rounded-full blur-3xl animate-pulse delay-1000"></div>
        </div>

        <div className="container mx-auto px-4 py-24 relative">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-5xl md:text-7xl font-bold mb-6 animate-fade-in">
              Ace Your Next
              <span className="block mt-2 bg-gradient-to-r from-yellow-300 to-pink-300 bg-clip-text text-transparent">
                Technical Interview
              </span>
            </h1>
            <p className="text-xl md:text-2xl mb-12 text-gray-100 max-w-2xl mx-auto">
              Practice with our AI interviewer, get real-time feedback, and land
              your dream job. Join thousands of successful candidates who
              improved their interview skills.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              {user ? (
                <Link to="/setup">
                  <Button
                    size="lg"
                    className="bg-white text-blue-600 hover:bg-gray-100 shadow-xl hover:shadow-2xl transform hover:scale-105 transition-all duration-300"
                  >
                    Start Practice Interview
                  </Button>
                </Link>
              ) : (
                <>
                  <Link to="/signup">
                    <Button
                      size="lg"
                      className="bg-white text-blue-600 hover:bg-gray-100 shadow-xl hover:shadow-2xl transform hover:scale-105 transition-all duration-300"
                    >
                      Get Started Free
                    </Button>
                  </Link>
                  <button
                    onClick={scrollToFeatures}
                    className="px-8 py-3 text-lg font-semibold rounded-lg border-2 border-white text-white hover:bg-white/10 transition-all duration-300"
                  >
                    Learn More
                  </button>
                </>
              )}
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mt-20">
              {stats.map((stat, index) => (
                <div key={index} className="text-center">
                  <div className="text-3xl md:text-4xl font-bold mb-2">
                    {stat.value}
                  </div>
                  <div className="text-sm md:text-base text-gray-200">
                    {stat.label}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section with ID */}
      <section id="features" className="py-24 bg-gray-50 scroll-mt-24">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">
              Why Choose{" "}
              <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                AI Interviewer
              </span>
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Everything you need to practice and perfect your interview skills
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <Card key={index} hover className="text-center group h-full">
                <div
                  className={`w-20 h-20 mx-auto mb-6 rounded-2xl bg-gradient-to-r ${feature.color} 
                  flex items-center justify-center text-4xl transform group-hover:scale-110 group-hover:rotate-3 transition-all duration-300 shadow-lg`}
                >
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      {!user && (
        <section className="py-20 bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-4xl font-bold text-white mb-6">
              Ready to Start Your Journey?
            </h2>
            <p className="text-xl text-white/90 mb-10 max-w-2xl mx-auto">
              Join thousands of candidates who have already improved their
              interview skills
            </p>

            <Link to="/signup">
              <Button
                variant="outline"
                size="lg"
                className="bg-white text-blue-600 hover:bg-gray-100 shadow-xl hover:shadow-2xl transform hover:scale-105 transition-all duration-300"
              >
                Create Free Account
              </Button>
            </Link>
          </div>
        </section>
      )}
    </div>
  );
};

export default Home;
